'use-client'
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
// import { Menu } from "@/components/Menu"
import { NavBar } from "@/components/NavBar"
import { Content } from "@/components/Content"
import { Header } from "@/components/Header"

import { AuthProvider } from "@/context/authContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

import { useAuth } from "@/context/authContext"
import { IUser } from "@/types/user"



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {



    return (
        <html lang="en">
            <body className={inter.className}>
            {/* <NavBar /> */}
        {/* <Content> */}
          <Header />
          {/* md:px-[2.8rem] */}
          <div className="md:ml-[420px] md:py-[3rem] px-[1rem] py-[2rem] container">
                <div className="">
                    <AuthProvider>
                    {children}
                    </AuthProvider>
                </div>
                </div>
            {/* </Content> */}
            </body>
        </html>
    )
}
