import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClientProvider } from "@/components/ClientProvider";
import FetchDataToStore from "@/components/FetchDataToStore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClientProvider>
            <html lang="en">
                <body className="">
                    <FetchDataToStore>
                        <div className="">{children}</div>
                    </FetchDataToStore>
                </body>
            </html>
        </ClientProvider>
    );
}
